### ISSUE TITLE
Doesn't work with password protected private keys

### ISSUE THREAD

**Issue by superboum** [soopsio/sshfs-go#1]
I tried `sshfs-go` (thanks for sharing!) but as I have a password protected private key, the command fails:

```
WARN[0000] mlockall() failed with ENOMEM                 error="cannot allocate memory"
2019/06/19 10:07:16 ssh: cannot decode encrypted private keys
INFO[0000] creating FUSE client for SSH Server           address="--- redacted ---"
panic: Failed to dial: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none password], no supported methods remain
```
I tried to register my key in a `ssh-agent` with:

```
ssh-agent
ssh-add
```
But it didn't help.

And the full stacktrace:

```
goroutine 1 [running]:
github.com/soopsio/sshfs-go/fs.NewSftp(0xc001973790, 0x7ffe62154a43, 0x16, 0x7ffe62154a68, 0x11, 0x0)
	/home/--- redacted ---/go/src/github.com/soopsio/sshfs-go/fs/fs.go:43 +0x120
github.com/soopsio/sshfs-go/fs.New(0xc001973790, 0x7ffe62154a7a, 0x1b, 0x7ffe62154a43, 0x16, 0x7ffe62154a68, 0x11, 0xc001950400, 0xc00000e600, 0xc0000649d0)
	/home/--- redacted ---/go/src/github.com/soopsio/sshfs-go/fs/fs.go:52 +0x43
github.com/soopsio/sshfs-go/cmd.glob..func4(0xf2ee40, 0xc0019ac1c0, 0x1, 0x7)
	/home/--- redacted ---/go/src/github.com/soopsio/sshfs-go/cmd/mount.go:47 +0x25e
github.com/spf13/cobra.(*Command).execute(0xf2ee40, 0xc0019ac150, 0x7, 0x7, 0xf2ee40, 0xc0019ac150)
	/home/--- redacted ---/go/src/github.com/spf13/cobra/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xf2f0c0, 0xf2f0c0, 0xc0019a9f88, 0x40729f)
	/home/--- redacted ---/go/src/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/--- redacted ---/go/src/github.com/spf13/cobra/command.go:864
github.com/soopsio/sshfs-go/cmd.Execute()
	/home/--- redacted ---/go/src/github.com/soopsio/sshfs-go/cmd/root.go:37 +0x32
main.main()
	/home/--- redacted ---/go/src/github.com/soopsio/sshfs-go/main.go:20 +0x20

```

Unfortunately, I don't have enough time to track the source of the bug/missing feature and fix it but at least I wanted to report it.

**Comment by nxsre** [comment]
Thanks for your attention. I will take time to solve this problem . Thank you!
